server:
    port: 8765

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

spring:
    application:
        name: "hr-gateway"
    cloud:
        gateway:
            routes:
            - id: hr-worker
              uri: http://localhost:8080/
              predicates:
              - Path=/workers/**

            - id: hr-payroll
              uri: http://localhost:8081/
              predicates:
              - Path=/payments/**